# Generated by Django 3.0.2 on 2020-01-12 19:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ISBN', models.CharField(help_text='13 Character <a href = "https://www.isbn-international.org/content/what-isbn">ISBN Number</a>', max_length=13, verbose_name='ISBN')),
                ('TitleName', models.CharField(max_length=100)),
                ('AuthorName', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['TitleName'],
            },
        ),
        migrations.CreateModel(
            name='BookRating',
            fields=[
                ('RatingID', models.IntegerField(primary_key=True, serialize=False)),
                ('Desc', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['RatingID'],
            },
        ),
        migrations.CreateModel(
            name='BookReader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=100)),
                ('RegistrationDate', models.DateField()),
                ('IsActive', models.CharField(max_length=1)),
                ('ValidFrom', models.DateField(default=datetime.date.today)),
                ('ValidDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='RentBooks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BorrowDate', models.DateField(blank=True, null=True)),
                ('ReturnDate', models.DateField(blank=True, null=True)),
                ('Book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Books.Book')),
                ('Reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Books.BookReader')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='Rating',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Books.BookRating'),
        ),
        migrations.AlterUniqueTogether(
            name='book',
            unique_together={('id', 'ISBN')},
        ),
    ]
